#!/bin/sh
exec 2>&1
if [ -n "$ALERTMANAGER_URL" ]; then
  exec s6-pause
fi
exec /opt/alertmanager/alertmanager \
  --config.file=/etc/nightwatch/alertmanager.yml \
  --storage.path=/var/nightwatch/alertmanager \
  --web.listen-address=0.0.0.0:9093
